require('dotenv').config();

const {
  APP_HOST,
  APP_PORT,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRATION_TIME,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRATION_TIME,
  TWILIO_SID,
  TWILIO_TOKEN,
  TWILIO_NUMBER,
} = process.env;
const database = require('./database');

module.exports = {
  APP: {
    HOST: APP_HOST || 'localhost',
    PORT: APP_PORT || 4005,
    JSON_REQUEST_LIMIT: '50mb',
    RAW_REQUEST_LIMIT: '50mb',
  },
  DATABASE: database,
  AUTH: {
    ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRATION_TIME,
    REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_EXPIRATION_TIME,
  },
  TWILIO: {
    SID: TWILIO_SID,
    TOKEN: TWILIO_TOKEN,
    NUMBER: TWILIO_NUMBER,
  },
};
